# This is a basic workflow to help you get started with Actions

name: CI - Build API and deploy API spec

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Redocly CLI
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest

      # Lint OpenAPI spec
      - name: Lint OpenAPI Spec        
        run: redocly lint api-specs/api-v1.yaml

      # Build docs
      - name: Build Docs
        run: |
          redocly bundle api-specs/api-v1.yaml --output docs/bundled-api-v1.yaml
          redocly build-docs docs/bundled-api-v1.yaml --output docs/index.html

